CREATE DATABASE shopping_list_db;

USE shopping_list_db;

CREATE TABLE shop_items
(
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	item VARCHAR(255) NOT NULL,
	purchased BOOLEAN DEFAULT FALSE,
	section VARCHAR (255) 
	date TIMESTAMP 
);

-- TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP

